// Enums - will be generated by Prisma, but defined here for now
export enum OrderSide {
  BUY = 'BUY',
  SELL = 'SELL',
}

export enum OrderType {
  LIMIT = 'LIMIT',
  MARKET = 'MARKET',
}

export enum OrderStatus {
  OPEN = 'OPEN',
  PARTIAL = 'PARTIAL',
  FILLED = 'FILLED',
  CANCELLED = 'CANCELLED',
}

// Session state enum for Telegraf session management
export enum UserState {
  IDLE = 'IDLE',
  CONNECTING_WALLET = 'CONNECTING_WALLET',
  SELECTING_PAIR = 'SELECTING_PAIR',
  ENTERING_AMOUNT = 'ENTERING_AMOUNT',
  ENTERING_PRICE = 'ENTERING_PRICE',
  CONFIRMING_ORDER = 'CONFIRMING_ORDER',
  VIEWING_ORDERS = 'VIEWING_ORDERS',
  CANCELLING_ORDER = 'CANCELLING_ORDER',
  // New states for token selection flow
  SELECTING_OFFER_TOKEN = 'SELECTING_OFFER_TOKEN',
  SELECTING_WANT_TOKEN = 'SELECTING_WANT_TOKEN',
  ENTERING_OFFER_AMOUNT = 'ENTERING_OFFER_AMOUNT',
  ENTERING_WANT_AMOUNT = 'ENTERING_WANT_AMOUNT',
}

export interface PendingOrder {
  type: OrderSide;
  orderType: OrderType;
  amount?: number;
  price?: number;
  pair?: string;
  baseCurrency?: string;
  quoteCurrency?: string;
  amountCurrency?: string;
  // New fields for token selection flow
  offerToken?: string;      // Token symbol user offers (e.g., "TON", "NOT")
  wantToken?: string;       // Token symbol user wants to get (e.g., "USDT", "BUILD")
  offerAmount?: number;     // Amount of offer token
  wantAmount?: number;      // Amount of want token
}

export interface UserSession {
  telegramId: number;
  state: UserState;
  walletAddress?: string;
  currentPair?: string;
  pendingOrder?: PendingOrder;
  lastActivity: Date;
  lastMessageId?: number;
  chatId?: number;
}

export interface OrderBookEntry {
  price: number;
  amount: number;
}

export interface OrderBook {
  pair: string;
  asks: OrderBookEntry[];
  bids: OrderBookEntry[];
}

export interface Config {
  telegramBotToken: string;
  databaseUrl: string;
  tonNetwork: string;
  tonApiKey: string;
  orderBookApiUrl: string;
  orderBookContractAddress: string;
  tonConnectManifestUrl: string;
  sessionSecret: string;
  jwtSecret: string;
  maxOrderAmount: number;
  minOrderAmount: number;
  apiRateLimit: number;
  open4devApiKey: string;
  open4devApiUrl: string;
  redisHost: string;
  redisPort: number;
  redisPassword?: string;
  redisTls: boolean;
  redisTtl: number;
  webhookDomain?: string;
  webhookPort: number;
  webhookSecret?: string;
}

// Wallet and Jetton types
export interface JettonBalance {
  symbol: string;
  name: string;
  balance: string;
  decimals: number;
  address?: string;
  price?: number;
  valueUsd?: number;
}

export interface WalletBalance {
  address: string;
  ton: string;
  jettons: JettonBalance[];
  totalValueUsd?: number;
  updatedAt: Date;
}

export interface WalletStats {
  address: string;
  totalOrders: number;
  openOrders: number;
  closedOrders: number;
  totalVolume: number;
  totalTrades: number;
  updatedAt: Date;
}

export interface WalletOrder {
  orderId: string;
  status: string;
  type: string;
  fromCoin: string;
  toCoin: string;
  amount: number;
  priceRate?: number;
  createdAt: string;
  deployedAt?: string;
  completedAt?: string;
}
